### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by RYLF** [dashingsoft/pyarmor-webui#2]
环境：win7 64、python2.7.13     pip方式安装
问题：启动后报错
Traceback (most recent call last):
  File "d:\python2713\install\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python2713\install\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\python2713\install\Scripts\pyarmor-webui.exe\__main__.py", line 5, in <module>
  File "d:\python2713\install\lib\site-packages\pyarmor\webui\server.py", line 26, in <module>
    from handler import RootHandler
  File "d:\python2713\install\lib\site-packages\pyarmor\webui\handler.py", line 9, in <module>
    from shlex import quote
ImportError: cannot import name quote

**Comment by jondy** [comment]
Fix in v0.9, please 升级到最新版本

**Comment by RYLF** [comment]
仍然没有解决。
C:\Users\RuoYun>pip install pyarmor-webui
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer
maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found a
t https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyarmor-webui
  Downloading pyarmor-webui-0.9.zip (319 kB)
     |████████████████████████████████| 319 kB 6.2 kB/s
<subprocess.STARTUPINFO instance at 0x03578030>
Requirement already satisfied: pyarmor>=5.9.3 in d:\python2713\install\lib\site-packages (from pyarmor-webui) (5.9.3)
Building wheels for collected packages: pyarmor-webui
  Building wheel for pyarmor-webui (setup.py) ... <subprocess.STARTUPINFO instance at 0x03574850>
done
  Created wheel for pyarmor-webui: filename=pyarmor_webui-0.9-py2-none-any.whl size=319073 sha256=3c0035610e6b7505240253fe6252ad
0309f1e26cafd0145ea88d792ecaa22008
  Stored in directory: c:\users\ruoyun\appdata\local\pip\cache\wheels\17\08\10\02428749e2de4507ee2c68cc7defed7019fa2306016a6b0af
b
Successfully built pyarmor-webui
Installing collected packages: pyarmor-webui
Successfully installed pyarmor-webui-0.9

C:\Users\RuoYun>pyarmor-webui
Traceback (most recent call last):
  File "d:\python2713\install\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python2713\install\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\python2713\install\Scripts\pyarmor-webui.exe\__main__.py", line 4, in <module>
  File "d:\python2713\install\lib\site-packages\pyarmor\webui\server.py", line 38, in <module>
    class HelperHandler(BaseHTTPRequestHandler):
  File "d:\python2713\install\lib\site-packages\pyarmor\webui\server.py", line 41, in HelperHandler
    root_handler = RootHandler(__config__)
  File "d:\python2713\install\lib\site-packages\pyarmor\webui\handler.py", line 107, in __init__
    super().__init__(config)
TypeError: super() takes at least 1 argument (0 given)

**Comment by jondy** [comment]
更新到 1.0.1，刚刚发布的，专门解决这个问题。

RuoYun <notifications@github.com> writes:

> 仍然没有解决。
> C:\Users\RuoYun>pip install pyarmor-webui
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your
> Python as Python 2.7 is no longer
> maintained. A future version of pip will drop support for Python 2.7. More details about Python 2
> support in pip, can be found a
> t https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Collecting pyarmor-webui
> Downloading pyarmor-webui-0.9.zip (319 kB)
> |████████████████████████████████| 319 kB 6.2 kB/s
> <subprocess.STARTUPINFO instance at 0x03578030>
> Requirement already satisfied: pyarmor>=5.9.3 in d:\python2713\install\lib\site-packages (from
> pyarmor-webui) (5.9.3)
> Building wheels for collected packages: pyarmor-webui
> Building wheel for pyarmor-webui (setup.py) ... <subprocess.STARTUPINFO instance at 0x03574850>
> done
> Created wheel for pyarmor-webui: filename=pyarmor_webui-0.9-py2-none-any.whl size=319073
> sha256=3c0035610e6b7505240253fe6252ad
> 0309f1e26cafd0145ea88d792ecaa22008
> Stored in directory:
> c:\users\ruoyun\appdata\local\pip\cache\wheels\17\08\10\02428749e2de4507ee2c68cc7defed7019fa2306016a6b0af
>
> b
> Successfully built pyarmor-webui
> Installing collected packages: pyarmor-webui
> Successfully installed pyarmor-webui-0.9
>
> C:\Users\RuoYun>pyarmor-webui
> Traceback (most recent call last):
> File "d:\python2713\install\lib\runpy.py", line 174, in _run_module_as_main
> "main", fname, loader, pkg_name)
> File "d:\python2713\install\lib\runpy.py", line 72, in run_code
> exec code in run_globals
> File "D:\python2713\install\Scripts\pyarmor-webui.exe_main.py", line 4, in 
> File "d:\python2713\install\lib\site-packages\pyarmor\webui\server.py", line 38, in 
> class HelperHandler(BaseHTTPRequestHandler):
> File "d:\python2713\install\lib\site-packages\pyarmor\webui\server.py", line 41, in HelperHandler
> root_handler = RootHandler(config)
> File "d:\python2713\install\lib\site-packages\pyarmor\webui\handler.py", line 107, in init
> super().init(config)
> TypeError: super() takes at least 1 argument (0 given)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
Best Regards
Jondy Zhao

**Comment by RYLF** [comment]
> 更新到1.0.1，刚刚发布的，专门解决这个问题。

非常感谢，现在已经可以运行了。
