### ISSUE TITLE
Waited awhile for this updated

### ISSUE THREAD

**Issue by MickCodes** [dashingsoft/pyarmor-webui#6]
8.0 + many versions have been released, but the WebUI Is relied on by me and many others on a team. When will this be updated? 8.0 seems to be officially released as you can pay for a pro license and more versions have been released since then.

**Comment by jondy** [comment]
The webui for Pyarmor 8.0 may be released between May 1 and May 31, it depends on the progress of Pyarmor 8.0 self. There are still lot of work for Pyarmor 8.0, for example, full test, full documentation and build core libraries for many other platforms.

**Comment by jondy** [comment]
pyarmor-webui 2.0+ has been released to support Pyarmor 8
