### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ExpressGit** [dashingsoft/pyarmor-webui#8]
1、免费版本

2、运行平台选择Linux86_64

3、运行报错
<img width="875" alt="image" src="https://github.com/dashingsoft/pyarmor-webui/assets/11694747/95825542-3424-4733-b8a5-69980963098f">

**Comment by ExpressGit** [comment]
<img width="809" alt="image" src="https://github.com/dashingsoft/pyarmor-webui/assets/11694747/e53b14f9-cb73-4b46-8db4-4c6b0a0c7f37">

**Comment by jondy** [comment]
缺少必要的信息
